name = "frontend"
compatibility_date = "2024-11-01"

pages_build_output_dir = ".open-next"

[vars]
NODE_ENV = "production"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "musafirmedia"